### ISSUE TITLE
Page Builder install button isn't working

### ISSUE THREAD

**Issue by Misplon** [siteorigin/panels-lite#2]
To replicate. Install North in an installation without Page Builder. In the Classic Editor click on the Page Builder tab, click on the Install button in the modal. When I tested, the Install button wasn't functional.

@AlexGStapleton Can you please, pick this one up? Thanks.

**Comment by AlexGStapleton** [comment]
This also happens in Vantage and the Custom Home Page. [This code ](https://github.com/WordPress/WordPress/blame/2a0489ec49c449894471a599c1811aaf0fcbbb22/wp-admin/js/updates.js#L2417-L2456) isn't triggering for some reason and the only change couldn't have caused this issue. I went over the entire file and I'm unable to spot a fix.

Do you know of any other plugin or theme that does this? I want to see how they've overcome this WP change.

**Comment by Misplon** [comment]
Perhaps try working the task as though it's a new task? I don't have a reference for someone else doing this, sorry.

**Comment by AlexGStapleton** [comment]
Sure. Does the install process need to remain exactly the same or are you okay with it changing slightly? I ask as using TGMPA to handle the install would make this process simpler and avoid WordPress updates potentially breaking this process again.

Alternatively, I can look at how they're handling things and see if I can replicate it (without the need to use TGMPA directly).

**Comment by Misplon** [comment]
It would be better if we could resolve this without depending on TGMPA. See what you can do. If the process has to change, it has to change.
